### PR TITLE
Add -x to wrap

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by cloudnautique** [comment]
You don't always need it. I'd rather it be set through an env variable or something else.

**Comment by hibooboo2** [comment]
So like an option you can pass into wrap and it will detect the env var?

On Tue, Feb 17, 2015 at 2:08 PM, Bill Maxwell <notifications@github.com>
wrote:

> You don't always need it. I'd rather it be set through an env variable or
> something else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rancherio/build-tools/pull/6#issuecomment-74753442>.
>



-- 

******************************************************

James Harris, Software Engineer

Tempe, AZ 85281

Tel: (480)-255-0632 (M), (480) 269-7232 (Google voice)

E-mail: wizardofmath@gmail.com

******************************************************

**Comment by cloudnautique** [comment]
No, like if an env var is set... so 
```
if [ ${WRAP_DEBUG} == "true" ]; then
 set -x
fi
```
or something similar

**Comment by hibooboo2** [comment]
Ok

**Pull request closed without merging**
